Repository master-csmi/2024-m1-parareal, pull requests merged in 2024-03, with the labels that each got.

#32 Add initial bibliography #3
  References.bib
Labels: documentation

#33 #4 add initial report
  .gitignore
  raport.tex
Labels: documentation

#34 #15 implement lorenz model
  .gitignore
  Lorenz_model.ipynb
Labels: documentation

#35 #4
  raport.tex
Labels: report

#37 #1 make the presentation
  presentation/images/butterfly.jpg
  presentation/presentation.tex
Labels: enhancement

#38 #21 update readme
  README.adoc
Labels: enhancement

#39 #21 update link in readme
  README.adoc
Labels: enhancement

#40 #1 update presentation and add roadmap
  presentation/images/roadmap.png
  presentation/presentation.tex
Labels: enhancement

#43 #21 update readme
  README.md
Labels: documentation
