Repository master-csmi/2024-m1-parareal, pull requests merged in 2024-04, with the labels that each got.

#51 #1
  presentation/images/parareal.png
  presentation/presentation.tex
Labels: documentation

#56 #17 #20
  Lorenz_model.ipynb
Labels: enhancement, good first issue, review

#57 #30
  raport.tex
Labels: documentation

#58 #24 #30
  References.bib
  raport.tex
Labels: documentation

#60 #18 add requirments.txt
  .gitignore
  requirements.txt
Labels: code-quality
